docs: update the branch name master to main in the docs
goharbor/harbor-operator pull request #1058
Opened 2023-07-17 09:53 UTC by chlins

Update the branch name from master to main for the documentations or code comments.

2023-07-17 12:55 UTC, MarcelMue approved these changes

2023-07-18 13:24 UTC, thcdrt requested changes

2023-07-20 02:31 UTC, chlins commented on apis/meta/v1alpha1/component.go
> +// https://github.com/kubernetes/community/blob/main/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties
Thanks, updated.

2023-07-20 08:16 UTC, thcdrt approved these changes

2023-07-27 02:01 UTC, merged