Rework reconcilation loop. Fix #131.
goharbor/harbor-operator pull request #339
Opened 2020-12-15 16:14 UTC by sguyennet

2020-12-16 03:27 UTC, steven-zou commented
@sguyennet 

Thanks for this fix. Would you please check and fix the failed CI checks? e.g: golint, generated files etc..

2020-12-21 03:21 UTC, bitsf commented
hi @sguyennet Can you also point out which lines in the fix is relative to reconcilation loop problems, that can help us review

2020-12-21 11:29 UTC, holyhope commented
There is at least 2 issues fixed in this PR:

1. Check that the resources is ready before applying the next one. (the check was broken because not called every time, so resource may be applied even if a dependency is not ready).
   Solved by reworking `pkg/controller/resource.ProcessFunc`.
2. The resource is changed on every apply because controller apply the template omitting fields in order to be filled by apiserver with default values. using this method, the object is modifiedon each apply because the `.metadata.managedFields` is updated.
   Solved by using [server-side apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/) instead of [`CreateOrUpdate`](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controllerutil/controllerutil.go#L197).
   Using server-side apply leads to many code removal since the *merge* of resources is done by kubernetes.
3. Removed the check before reconciling resources to skip the loop if no changes detected. See (`pkg/controller/status.go`).
   There was a check to ignore some reconciliation events to *optimize* the controller. By design, this check cannot detect changes properly.

2020-12-22 12:36 UTC, steven-zou commented
@sguyennet @holyhope 

CI is still failing. Would you please check and fix the failures ASAP? Thanks a lot!

2021-01-04 08:22 UTC, steven-zou commented
@sguyennet

Any updates about this PR (When can we fix the CI failures)? We're heading to the FC deadline.

2021-01-14 14:02 UTC, holyhope requested changes

2021-01-14 14:02 UTC, holyhope commented on controllers/goharbor/internal/test/certificate.go
> +/*
IMO you should use fucntions from `controllers/goharbor/test_utils.go`, there is bugs here :-)

2021-01-15 09:57 UTC, holyhope approved these changes

2021-01-18 06:36 UTC, steven-zou approved these changes
LGTM

2021-01-18 06:36 UTC, merged