feature(redis) sentinel support
goharbor/harbor-operator pull request #348
Opened 2020-12-17 16:55 UTC by bitsf

close #160 
feature(redis) sentinel support

2020-12-17 16:56 UTC, bitsf commented
## current core
_REDIS_URL_REG=redis://:diwhfnwr@harborcluster-sample-redis/2

_REDIS_URL=harborcluster-sample-redis:6379,100,diwhfnwr,0,30

## target core
_REDIS_URL_REG=redis+sentinel://:diwhfnwr@rfs-harborcluster-sample-redis/mymaster/1

_REDIS_URL_CORE=redis+sentinel://:diwhfnwr@rfs-harborcluster-sample-redis/mymaster/0

## current jobservice
config.yml
```
worker_pool:
  backend: "redis"

  redis_pool:
    redis_url: redis://:edjihfbi@harborcluster-sample-redis/1
    namespace: jobservice::cluster-sample-ns::harborcluster-sample-harbor-harbor
    idle_timeout_second: 30
```

## target jobservice
config.yml
```
worker_pool:
  backend: "redis"

  redis_pool:
    redis_url: redis+sentinel://:edjihfbi@rfs-harborcluster-sample-redis/mymaster/2z?idle_timeout_seconds=30
    namespace: jobservice::cluster-sample-ns::harborcluster-sample-harbor-harbor
    idle_timeout_second: 30
```

## current registry
/etc/registry/config.yml
```
redis:
  addr: "harborcluster-sample-redis:6379"
  # password: setted through environment variable
  db: 1
  pool:
    maxidle: 3
    maxactive: 5
    idletimeout: 30s
```

## target registry
```
redis:
  # sentinel hosts with comma
  addr: rfs-harborcluster-sample-redis:26379
  sentinelMasterSet: mymaster
  readtimeout: 10s
  writetimeout: 10s
  dialtimeout: 10s
  password: 123
  db: 1
```

2020-12-18 07:57 UTC, steven-zou requested changes
do changes?

2020-12-18 07:57 UTC, steven-zou commented on config/config/assets/registry-config.yaml.tmpl
> +  sentinelMasterSet: mymaster
Here should be a variable, correct?

2020-12-18 09:01 UTC, chlins approved these changes
LGTM

2020-12-19 04:19 UTC, steven-zou approved these changes
Approved

2020-12-19 04:19 UTC, merged