fix(harbor class) Close #399
goharbor/harbor-operator pull request #425
Opened 2021-01-28 15:40 UTC by sguyennet

Signed-off-by: Simon Guyennet <simon.guyennet@corp.ovh.com>

2021-01-28 16:10 UTC, holyhope requested changes

2021-01-28 16:10 UTC, holyhope commented on pkg/controller/mutation.go
> +		mutate.AppendMutation(mutation.GetAnnotationsMutation(HarborClassAnnotation, className))
```suggestion
		mutate.AppendMutation(mutation.GetAnnotationsMutation(goharborv1alpha2.HarborClassAnnotation, className))
```

2021-01-28 16:10 UTC, holyhope commented on pkg/controller/mutation.go
> +	HarborClassAnnotation = "goharbor.io/harbor-class"
```suggestion
```

2021-01-28 16:13 UTC, holyhope commented on pkg/controller/mutation.go
> +	WarningValueTmpl      = "⚠️ This Resource is managed by *%s* ⚠️"
```suggestion
	WarningAnnotation = "goharbor.io/warning"
	WarningValueTmpl  = "⚠️ This Resource is managed by *%s* ⚠️"
```

2021-01-28 16:14 UTC, holyhope approved these changes

2021-01-28 16:32 UTC, holyhope approved these changes

2021-01-30 14:35 UTC, steven-zou approved these changes
LGTM

2021-01-30 14:35 UTC, merged