feat(loadblance) support to expose service via load balancer
goharbor/harbor-operator pull request #439
Opened 2021-02-09 01:07 UTC by Ghostbaby

support to expose service via load balancer

fix #178

Signed-off-by: zhuhuijun <zhuhuijunzhj@gmail.com>

2021-02-09 02:17 UTC, heww commented on controllers/goharbor/harbor/loadblance.go
> +	if harbor.Spec.Expose.Core.LoadBalancer == nil {
harbor.Spec.Expose.Core.LoadBalancer != nil but harbor.Spec.Expose.Core.LoadBalancer.Enable may be false.

2021-03-02 06:07 UTC, steven-zou requested changes
we can do some refactor to the code

2021-03-02 06:07 UTC, steven-zou commented on controllers/goharbor/harbor/loadblance.go
> +func (r *Reconciler) AddPortalLB(ctx context.Context, harbor *goharborv1alpha2.Harbor, portal Portal) (NotarySignerLB, error) {
@Ghostbaby 

It seems functions `addLB` and `getLB` can be general functions that can be used among core,total, notary and singer.

2021-03-04 05:51 UTC, steven-zou commented on controllers/goharbor/harbor/loadblance.go
> +func (r *Reconciler) AddPortalLB(ctx context.Context, harbor *goharborv1alpha2.Harbor, portal Portal) (NotarySignerLB, error) {
If it is hard to do, then keeping it as it was is ok for me.

2021-03-10 10:43 UTC, steven-zou commented
@Ghostbaby per our discussion, let's remove the LB support out of the 1.0 release. You can close this PR.

2021-03-17 13:43 UTC, steven-zou commented
Let's find a better way in future to support LB. Close this now.

2021-03-17 13:43 UTC, closed without merging