feat(certificate) Use cert-manager.io/v1
goharbor/harbor-operator pull request #449
Opened 2021-02-12 09:28 UTC by holyhope

Signed-off-by: Pierre Péronnet <pierre.peronnet@ovhcloud.com>

2021-02-20 04:58 UTC, bitsf approved these changes

2021-02-20 05:04 UTC, bitsf commented on apis/goharbor.io/v1alpha2/notaryserver_types.go
> +	// +kubebuilder:default=ECDSA
CI seems failed because of this
![Uploading image.png…]()

2021-02-20 05:04 UTC, bitsf requested changes
ci failed

2021-03-01 10:29 UTC, steven-zou commented
@holyhope 

Fix CI failures?

2021-03-15 14:00 UTC, steven-zou commented
@holyhope 

Any progress of fixing this PR?

2021-03-17 13:32 UTC, steven-zou commented
Fixing by PR https://github.com/goharbor/harbor-operator/pull/502

2021-03-17 13:41 UTC, closed without merging