fix(pg) remove pg status check
goharbor/harbor-operator pull request #476
Opened 2021-03-04 13:32 UTC by Ghostbaby

remove pg status check

fix #474

Signed-off-by: zhuhuijun <zhuhuijunzhj@gmail.com>

2021-03-05 02:53 UTC, steven-zou requested changes
@Ghostbaby 

Please also remove the useless const values defined in this file

2021-03-05 02:53 UTC, steven-zou commented on pkg/cluster/controllers/database/readiness.go
>  	p.Log.Info("Database already ready.",
```suggestion
	p.Log.Info("Database is ready.",
```

2021-03-05 02:53 UTC, steven-zou commented on pkg/cluster/controllers/database/readiness.go
> -	if pg.Status.PostgresClusterStatus != "Running" {
The staus checking here should not be deleted.

```
// Define this status as a const 
PsqlRunningStatus = "Running"

// --- some code

properties := &lcm.Properties{}
crStatus := lcm.New(goharborv1alpha2.DatabaseReady).WithProperties(*properties)

// Not ready yet
if pg.Status.PostgresClusterStatus != PsqlRunningStatus {
  crStatus.WithStatus(corev1.ConditionFalse).
  WithReason("database is not ready").
  WithMessage(fmt.Sprintf("psql is %s", pg.Status.PostgresClusterStatus ))

return crStatus
}

// --- some code here 
p.Log.Info("Database is ready.",
		"namespace", p.HarborCluster.Namespace,
		"name", p.HarborCluster.Name)

	if err := p.DeployComponentSecret(conn, getDatabasePasswordRefName(name)); err != nil {
		return nil, err
	}

	addProperties(name, conn, properties)

	crStatus := WithStatus(corev1.ConditionTrue).
                WithReason("database is ready").
		WithMessage("harbor component database secrets are created.").
		WithProperties(*properties)

	return crStatus, nil
```

2021-03-08 01:36 UTC, steven-zou approved these changes
LGTM

2021-03-08 02:50 UTC, heww approved these changes

2021-03-08 02:50 UTC, merged