feature(storage): support gcs blob storage
goharbor/harbor-operator pull request #810
Opened 2021-11-14 15:15 UTC by soulseen

Signed-off-by: soulseen <zhuxiaoyang1996@gmail.com>

2021-11-17 06:23 UTC, cndoit18 requested changes

2021-11-17 06:23 UTC, cndoit18 commented on apis/goharbor.io/v1beta1/chartmuseum_types.go
> +	Bucket string `json:"bucket,omitempty"`
remove `omitempty`

2021-11-17 06:23 UTC, cndoit18 commented on apis/goharbor.io/v1beta1/chartmuseum_types.go
> +	KetDataSecretRef string `json:"ketDataSecretRef,omitempty"`
remove `omitempty`

2021-11-17 06:23 UTC, cndoit18 commented on apis/goharbor.io/v1beta1/harborcluster_types.go
> +	// +kubebuilder:validation:Enum={MinIO,S3,Swift,FileSystem,Azure, Gcs}
```suggestion
	// +kubebuilder:validation:Enum={MinIO,S3,Swift,FileSystem,Azure,Gcs}
```

2021-12-09 07:40 UTC, cndoit18 approved these changes
LGTM

2021-12-13 16:15 UTC, bitsf approved these changes

2021-12-14 03:17 UTC, merged