Fix/clair updater and ingress cert
goharbor/harbor-operator pull request #87
Opened 2020-08-27 00:38 UTC by steven-zou

- add cert manager related annotations to the ingresses (core and notary)
- add host info to the ingress TLS part
- remove `REGISTRY_HTTP_HOST ` ENV VAR from registry deployment
- update clair updater interval to `1h` to enable CVE DB updating process

Signed-off-by: Steven Zou <szou@vmware.com>

2020-08-27 00:43 UTC, steven-zou commented
@holyhope 

Would u please take a look at this or? thanks!

2020-08-28 14:24 UTC, holyhope requested changes
Hello @steven-zou,

Can you please reopen the PR to 0.5.1 branch please?
Master is now on 1.0 :-)

2020-08-29 02:38 UTC, steven-zou commented
> Hello @steven-zou,
> 
> Can you please reopen the PR to 0.5.1 branch please?
> Master is now on 1.0 :-)

@holyhope

Does this mean the 1.0 is ready for release? If yes, we'll take time to deploy and test it next week.

2020-08-29 02:44 UTC, steven-zou commented
Use this new PR to merge code: https://github.com/goharbor/harbor-operator/pull/92

2020-08-29 02:44 UTC, closed without merging